POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 
# {
#     "title": "Things I Don't Know as of 2018",
#     "author": "Dan Abramov", 
#     "url": "https://overreacted.io/things-i-dont-know-as-of-2018/"
# }

# { 
#     "title": "You Don't Know What You Don't Know",
#     "author": "Arto Hellas",
#     "url": "https://www.forbes.com/sites/brucekasanoff/2018/03/21/you-dont-know-wh…"
# }

{
    "title": "The Two Reacts",
    "author": "Danny Abramov",
    "url": "https://overreacted.io/the-two-reacts/"
}